name: Node.js Build Check

on:
  push:
    branches: [ '**' ]  # This specifies that the action should run on pushes to any branch

jobs:
  build:
    runs-on: ubuntu-latest  # You can specify another OS if needed

    strategy:
      matrix:
        node-version: [21.5.0]  # Specify the Node.js version(s) you want to use

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci  # or npm install

    - name: Run build
      run: npm run build
